# Generated by Django 5.1.4 on 2025-01-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='raiting',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='58596', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
