# Generated by Django 5.1.4 on 2025-01-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_remove_product_id_product_raiting_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='71153', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
